FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./ ./

RUN go test ./...

WORKDIR /app/cmd/gophermart
RUN go build -buildvcs=false -o /gophermart

FROM alpine:latest
WORKDIR /root/

RUN apk update && apk add --no-cache bash

COPY --from=builder /gophermart .

CMD ["./gophermart"]
